language: ruby
rvm:
- 3.0
- 2.7
- 2.6
- 2.5
- 2.4
- jruby-9.2
before_script:
- make install
script:
- make test
deploy:
  provider: rubygems
  api_key: "$RUBYGEMS_API_KEY"
  gem: smtpapi
  on:
    tags: true
    rvm: '2.4'
    skip_cleanup: true
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: F5/iPScUfgbtjvfAOrU7gyptywZ2JvuC3Wil2I0eebmYTzcg5is0uDwViF1Qt1hQ5yQeKEtza8R7j+ug8MkANjWQOL3w5zMXBKL6UCHV1YLyDW47AAaELouz7yoTjZtu7VvbxPYGxk47eNCRlRfAMHl9VJd1SepXlrTQtwtOHVw=
