language: ruby
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - jruby-9.2
before_script:
  - make install
script:
  - make test
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: smtpapi
  on:
    tags: true
    rvm: '2.4'
    skip_cleanup: true

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: kyDurUDtXcp+6SfpFeszmzRZEpl2IOFqevGelhKVfx7j+M+p1wvPCkv9vnSdpKaZbQ80EKORxS4ZsnKUL9/yOP2uF9mrzB/DCfzFynw/IVfBejM8nkbf/CmosFh0SkkLuwotaPeqMhAtg1J8Avk1HVKJmihaJfkD6kzQ3PSyKlw=
